Fixes for Nexogen.Libraries.Metrics.Grpc
nexogen-international/Nexogen.Libraries.Metrics pull request #47
Opened 2020-04-23 10:31 UTC by bastianeicher

This PR fixes the logic used to split gRPC service and method names.

I also adjusted the namespace to match the package name change from #46.

2020-04-27 17:54 UTC, ahoka requested changes
Thanks, I only have one comment. Sorry for missing the namespaces earlier.

2020-04-27 17:54 UTC, ahoka commented on Nexogen.Libraries.Metrics.Grpc/MetricsBase.cs
> +            string serviceName = string.Join(".", split.Take(split.Length - 1));
Would you please add a unit test for this logic, with real world examples? I think that would be a valuable.

2020-04-28 09:07 UTC, bastianeicher commented
I've done some extensive refactoring to make the library more testable and added unit tests.

2020-04-28 11:56 UTC, ahoka approved these changes
Thanks.

2020-04-28 11:56 UTC, merged

2020-04-28 12:06 UTC, ahoka commented
I have created a new release with these changes and unlisted the old version with the incorrect namespace.

2020-04-28 12:48 UTC, bastianeicher commented
Thanks :)